### ISSUE TITLE
module 'psutil' has no attribute 'sensors_temperatures'

### ISSUE THREAD

**Issue by Biswajit-Banerjee** [urosjevremovic/CPU_temperature_checker#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\python3\lib\site-packages\AvgCpuTemp\avg_cpu_temp.py", line 25, in get_current_cpu_temp
    for stamp, value_in_c in itertools.islice(zip(timestamp, sensor), 1):
  File "C:\python3\lib\site-packages\AvgCpuTemp\avg_cpu_temp.py", line 14, in __next__
    return psutil.sensors_temperatures()['k10temp'][0][1]
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'

**Comment by xeno27** [comment]
psutil dont suport sensor´s under windows ... 
see : [psutil doc](https://psutil.readthedocs.io/en/latest/)

**Comment by arch-user-france1** [comment]
nah that's amd only intel doesn't call those sensors like that, that's why it fails
